### PR TITLE
New nft-card styling

### PR DESCRIPTION
**Pull request by spenpo**
@gavinspr just a rough draft so that we can start talking about how we want this to look. if you click on the legend image the info behind will appear. lmk what you think

TICKET: https://trello.com/c/moDWJfD4/1-all-legends-display-nft-data-in-card-component

### CODE REVIEW

**Comment by gavinspr** [comment]
I like the size of the cards more than the previous size. I do think we should be displaying some information on the card without user interaction though. Such as the name and ID up top, and possibly some light information below the image.

Clicking on the image could redirect to a component that dynamically renders specific information about the legend.There we can display all information about the legend. Such as purchase history, family tree, etc. Similar to how open sea does https://opensea.io/assets/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb/4380
Or we could make it a modal? But I think a whole page for the legend would make sense

I was originally thinking the menu button would be a drop down rather than show/collapse a section with actionable buttons. I like it but I don't know how I feel about the effect causing a shift in the row below it.

Also I wonder if there is an easy way to do like a "shiny" card effect for Legendary Legends

**Comment by spenpo** [comment]
> I like the size of the cards more than the previous size. I do think we should be displaying some information on the card without user interaction though. Such as the name and ID up top, and possibly some light information below the image.
> 
> Clicking on the image could redirect to a component that dynamically renders specific information about the legend.There we can display all information about the legend. Such as purchase history, family tree, etc. Similar to how open sea does https://opensea.io/assets/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb/4380 Or we could make it a modal? But I think a whole page for the legend would make sense

got it I'll make some tweaks and set up a legend component with new route

> I was originally thinking the menu button would be a drop down rather than show/collapse a section with actionable buttons. I like it but I don't know how I feel about the effect causing a shift in the row below it.

not sure what you mean by this. what do you want the dropdown to do exactly?

> Also I wonder if there is an easy way to do like a "shiny" card effect for Legendary Legends

Yes I was thinking the same. do you have a link to something shiny that you want me to copy? maybe we should ask the team about this? gold trim is another possibility

**Comment by gavinspr** [comment]
@spope851 for the dropdown I was just thinking it would be a menu with the actions in it(Blend, Trade, etc) nothing fancy. But open to other ideas

And for the "shiny" haven't looked at any effects yet, but I will. And deff good to get the team input on how we display it is a Legendary. I like the idea of gold trim

**Comment by spenpo** [comment]
@gavinspr still not entirely sure what you mean by dropdown and menu, but is this more like what you were thinking? I put each action in a dropdown and then an execute button to the right of the dropdown. try it out. if not do you have an example?

**Comment by gavinspr** [comment]
@spope851 Nothing fancy, just a dropdown menu. Small icon in top right corner > user clicks it > menu appears (like you currently have) > user clicks on an element inside the menu > *action takes place* 

dropdown

^ but where it says "dropdown" I think we can just use an icon like the three lines you had previously or "three dots" the other commonly seen icon for menus

**Pull request closed without merging**
